name : Node continuous integration / Auto tests
on: [push, pull_request]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: yarn install
      - run: yarn test